name : employee-management-system

services:

    mongo:
      image: mongo:7.0.12
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      networks:
        - EMS
      
    api-server:
      build:
        context: ./server
        dockerfile: Dockerfile
      restart: unless-stopped
      env_file: ./server/.env
      volumes:
        - ./server:/app
        - /app/node_modules
      ports:
        - 3000:3000
      networks:
        - EMS
      depends_on:
        - mongo

      client:
        build:
          context: ./client
          dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
          - ./client:/app
          - /app/node_modules
        ports:
          - 5173:5173
        command: npm run dev -- --host
        networks:
          - EMS
        depends_on:
          - api-server


volumes:
  mongo-data:

networks:
  EMS:
    driver: bridge